Ability to specify busybox image for etcd init containers
cilium/cilium-etcd-operator pull request #50
Opened 2019-03-15 16:05 UTC by trevex

As requested in Slack this PR adds the ability to specify the busybox image of the etcd init container.

The change is fairly simple and introduces a flag and env variable to override the default busybox image.

2019-03-15 18:26 UTC, aanm approved these changes

2019-03-15 18:27 UTC, aanm requested changes
@treve thanks for the changes! can you sign-off your commit please?

2019-03-17 08:00 UTC, trevex commented
Signed off the commit and also rebased, because there was a merge request with latest master.

2019-03-17 08:01 UTC, trevex commented
Unfortunately I can not mark the change request as solved, because github can not list the requested changes anymore, because the related commit was changed by a force push...

2019-03-18 19:42 UTC, aanm approved these changes

2019-03-18 19:42 UTC, merged